# Generated by Django 2.2.1 on 2019-07-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucircle', '0003_userprofile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='year',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, default='Shalamar Hospital', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='title',
            field=models.CharField(blank=True, default='Doctor', max_length=1000, null=True),
        ),
    ]
