# Generated by Django 2.2.1 on 2019-07-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucircle', '0005_following_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_hospital_admin',
            field=models.BooleanField(default=False),
        ),
    ]
