# Generated by Django 2.2.1 on 2019-08-01 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nucircle', '0006_userprofile_is_hospital_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='user_1',
        ),
        migrations.RemoveField(
            model_name='friends',
            name='user_2',
        ),
        migrations.RemoveField(
            model_name='job',
            name='user',
        ),
        migrations.RemoveField(
            model_name='job_application',
            name='job',
        ),
        migrations.RemoveField(
            model_name='job_application',
            name='user',
        ),
        migrations.RemoveField(
            model_name='job_tag',
            name='job',
        ),
        migrations.RemoveField(
            model_name='job_tag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='recruitment',
            name='job',
        ),
        migrations.RemoveField(
            model_name='recruitment',
            name='user',
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
        migrations.DeleteModel(
            name='Friends',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='Job_Application',
        ),
        migrations.DeleteModel(
            name='Job_Tag',
        ),
        migrations.DeleteModel(
            name='Recruitment',
        ),
    ]
