# Generated by Django 2.2.1 on 2019-08-01 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nucircle', '0007_auto_20190801_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='interest',
        ),
        migrations.RemoveField(
            model_name='interest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='discipline',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='graduation_year',
        ),
        migrations.DeleteModel(
            name='AllInterests',
        ),
        migrations.DeleteModel(
            name='Interest',
        ),
    ]
