# Generated by Django 2.2.1 on 2019-08-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucircle', '0011_auto_20190807_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='post_comment',
            name='text',
            field=models.CharField(default='comment...', max_length=1000),
        ),
    ]
