from django.conf.urls import url
from . import views
from django.urls import path, include

app_name = 'nucircle'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^profile/(?P<user_id>[0-9]+)/$', views.profile, name='profile'),
    url(r'^newsfeed/$', views.newsfeed, name='newsfeed'),
    url(r'^network/$', views.network, name='network'),
    # form urls
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^profile/(?P<user_id>[0-9]+)/(?P<error>[a-zA-Z0-9.!-_@ ]+)/$', views.profile, name='profile'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^login/$', views.login, name='login'),
    url(r'^update_profile_image/$', views.update_profile_image, name='update_profile_image'),
    url(r'^edit_personal_info/$', views.edit_personal_info, name='edit_personal_info'),
    url(r'^add_education/$', views.add_education, name='add_education'),
    url(r'^edit_education/$', views.edit_education, name='edit_education'),
    url(r'^edit_education/(?P<education_id>[0-9]+)/$', views.edit_education, name='edit_education'),
    url(r'^add_accomplishment/$', views.add_accomplishment, name='add_accomplishment'),
    url(r'^edit_accomplishment/$', views.edit_accomplishment, name='edit_accomplishment'),
    url(r'^edit_accomplishment/(?P<accomplishment_id>[0-9]+)/$', views.edit_accomplishment, name='edit_accomplishment'),
    url(r'^add_experience/$', views.add_experience, name='add_experience'),
    url(r'^edit_experience/$', views.edit_experience, name='edit_experience'),
    url(r'^edit_experience/(?P<experience_id>[0-9]+)/$', views.edit_experience, name='edit_experience'),
    url(r'^add_project/$', views.add_project, name='add_project'),
    url(r'^edit_project/$', views.edit_project, name='edit_project'),
    url(r'^edit_project/(?P<project_id>[0-9]+)/$', views.edit_project, name='edit_project'),
    url(r'^add_skill/$', views.add_skill, name='add_skill'),
    url(r'^edit_skill/$', views.edit_skill, name='edit_skill'),
    url(r'^edit_skill/(?P<skill_id>[0-9]+)/$', views.edit_skill, name='edit_skill'),
    url(r'^add_interest/$', views.add_interest, name='add_interest'),
    url(r'^edit_interest/$', views.edit_interest, name='edit_interest'),
    url(r'^search_results/$', views.search_results, name='search_results'),
    url(r'^add_post/$', views.add_post, name='add_post'),
    url(r'^get_post/$', views.get_post, name='get_post'),
    url(r'^delete_post/$', views.delete_post, name='delete_post'),
    url(r'^api/jobs/$', views.JobView.as_view()),
    url(r'^api/jobs/(?P<job_id>[0-9]+)/$', views.JobDetailView.as_view()),
    url(r'^api/usersandprofiles/$', views.UserSearchView.as_view()),
    url(r'^api/applicants/(?P<job_id>[0-9]+)/$', views.JobApplicantListView.as_view()),
    url(r'^myfiles/$', views.myfiles, name='myfiles'),
    url(r'^myfiles/delete/(?P<pk>[0-9]+)$', views.delete_file, name='delete_file'),
    url(r'^myfiles/upload/$', views.upload_file, name='upload_file'),
    url(r'^follow_unfollow/ajax$', views.follow_unfollow, name='follow_unfollow'),
    url(r'^hospital_settings/$', views.hospital_settings, name='hospital_settings'),
    url(r'^change_password/$', views.change_password, name='change_password'),
    url(r'^super_user_settings/$', views.super_user_settings, name='super_user_settings'),
    url(r'^change_password_hospital_settings/ajax$', views.change_password_hospital_settings, name='change_password_hospital_settings'),
    url(r'^delete_user_hospital_settings/ajax$', views.delete_user_hospital_settings, name='delete_user_hospital_settings'),
    url(r'^signup_hospital_admin/ajax$', views.signup_hospital_admin, name='signup_hospital_admin'),
    url(r'^create_users_csv/ajax$', views.create_users_csv, name='create_users_csv'),
    url(r'^members_directory/$', views.members_directory, name='members_directory'),
    url(r'^check_code/$', views.check_code, name='check_code'),
    url(r'^like_dislike_post/$', views.like_dislike_post, name='like_dislike_post'),
    url(r'^get_post_ajax/$', views.get_post_ajax, name='get_post_ajax'),
    url(r'^get_comments_post/$', views.get_comments_post, name='get_comments_post'),
    url(r'^submit_comments_post/$', views.submit_comments_post, name='submit_comments_post'),
    url(r'^delete_comment_from_post/$', views.delete_comment_from_post, name='delete_comment_from_post'),
    url(r'^edit_comment_from_post/$', views.edit_comment_from_post, name='edit_comment_from_post'),
]
