# Generated by Django 2.2.1 on 2019-06-25 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chat_chat_messages_chat_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='title',
            field=models.CharField(default='NO-NAME', max_length=100),
        ),
    ]
