# Generated by Django 2.2.1 on 2019-06-26 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20190625_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='title',
        ),
        migrations.AddField(
            model_name='chat',
            name='isSingleChat',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Group_Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatTitle', models.CharField(default='NO-NAME', max_length=100)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_group', to='chat.Chat')),
            ],
        ),
    ]
