# Generated by Django 2.2.1 on 2019-07-01 15:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20190626_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_participants',
            name='chat_cleared_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 1, 15, 46, 13, 127672, tzinfo=utc)),
        ),
    ]
