# Generated by Django 2.2.1 on 2019-07-01 15:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chat_participants_chat_cleared_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_participants',
            name='chat_cleared_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
