# Generated by Django 2.2.1 on 2019-07-01 18:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20190701_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_participants',
            name='chat_cleared_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
