# Generated by Django 2.2.1 on 2019-07-02 00:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20190701_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_messages',
            name='msg_created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 2, 5, 21, 57, 326026)),
        ),
        migrations.AlterField(
            model_name='chat_participants',
            name='chat_cleared_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 2, 5, 21, 57, 325029)),
        ),
    ]
