# Generated by Django 2.2.1 on 2019-07-03 10:06

import chat.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_auto_20190702_0540'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_chat',
            name='group_img',
            field=models.ImageField(blank=True, default='no_image.png', null=True, upload_to=chat.models.group_directory_path),
        ),
        migrations.AlterField(
            model_name='chat_participants',
            name='chat_cleared_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 3, 15, 6, 5, 87464)),
        ),
    ]
