# Generated by Django 2.2.1 on 2019-07-04 03:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucircle', '0002_file'),
        ('chat', '0012_auto_20190704_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='files',
            field=models.ManyToManyField(related_name='files', to='nucircle.File'),
        ),
        migrations.AlterField(
            model_name='chat_participants',
            name='chat_cleared_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 4, 8, 49, 6, 489611)),
        ),
    ]
