# Generated by Django 2.2.1 on 2019-08-01 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0021_auto_20190801_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_participants',
            name='chat_cleared_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 1, 13, 13, 32, 510308)),
        ),
    ]
