# Generated by Django 2.2.1 on 2019-08-06 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0022_auto_20190801_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_participants',
            name='chat_cleared_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 6, 19, 40, 45, 162563)),
        ),
    ]
